name: Manage issue-coupled branches

on:
  issues:
    types: [opened]
  push:
    branches-ignore:
      - dev
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: theonejonahgold/issue-branch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name_pattern: iss#{number}
