name: Manage sprint

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  start-sprint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Start sprint'
        uses: theonejonahgold/milestone-sprint@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project_name: Project
